version: '3'
services:
  redis:
    image: redis:7
    container_name: colearn-redis-cache
    ports:
      - "6379:6379"
    volumes:
      - colearn-redis-data:/data

volumes:
  colearn-redis-data:
